version: "3.7"
services:

  ###############################################
  # Used as provisioner and "external" dns server
  # ------------------------------------------------
  core:
    hostname: core
    build:
      context: .
      dockerfile: node/Dockerfile
    volumes: 
    - ./provision:/ws/provision
    - ./docker-compose.yaml:/ws/docker-compose.yaml
    - ./node/identity:/ws/identity
    - ./dns/entrypoint.sh:/entrypoint.sh
    - ./dns/Corefile:/ws/Corefile
    - ./node/resolv.conf:/ws/resolv.conf
    # entrypoint: /bin/bash
    environment:
      KUBECONFIG: ./kube_config_cluster.yml
    working_dir: /ws
    stdin_open: true
    tty: true


  ##################################################
  # Rancher server
  # ------------------------------------------------
  rancher:
    image: rancher/rancher
    ports:
    - "8443:443"
    # - "8080:80"
    # volumes: [ ./node/identity:/ws/identity ] # rancher doesn't provision via rke existing nodes


  ##################################################
  # Nodes being used as if they were VMs or physical
  # nodes for rke clusters
  # ------------------------------------------------
  node-1: &node
    hostname: node-1
    build:
      context: .
      dockerfile: node/Dockerfile
    ports:
    - "2201:22"
    - "80:80" # Ingress. Use anything.lvh.me for ingress and always have at least node-1 as a worker
    - "443:443" # Ingress. Use anything.lvh.me for ingress and always have at least node-1 as a worker
    # depends_on:
    # - core
    # - rancher
    volumes:
    - &vol-resolv ./node/resolv.conf:/etc/resolv.conf
    - &vol-pv ./volumes:/opt/local-path-provisioner # Simple PVC support mapped to host
    # - node-1-rke:/opt/rke
    # - node-1-kubelet:/var/lib/kubelet
    # - node-1-docker:/var/lib/docker
    stdin_open: true
    tty: true
    privileged: true
    sysctls:
      # https://docs.docker.com/compose/compose-file/
      # https://the.binbashtheory.com/rke-dind/
      # https://github.com/rancher/rke/blob/master/dind/dind.go#L78
      net.ipv4.conf.all.rp_filter: "1"
  # ------------------------------------------------
  node-2:
    <<: *node
    hostname: node-2
    ports:
    - "2202:22"
    # volumes: [ *vol-resolv, *vol-pv, node-2-rke:/opt/rke, node-2-kubelet:/var/lib/kubelet, node-2-docker:/var/lib/docker]
  # ------------------------------------------------
  node-3:
    <<: *node
    hostname: node-3
    ports:
    - "2203:22"
  # ------------------------------------------------
  node-4:
    <<: *node
    hostname: node-4
    ports:
    - "2204:22"
    - "4080:80" # This would be the ingress for a second cluster that node-4 is part of as a worker (cl-ha-rancher scenario)
    - "4443:443" # This would be the ingress for a second cluster that node-4 is part of as a worker (cl-ha-rancher scenario)
  # ------------------------------------------------
  node-5:
    <<: *node
    hostname: node-5
    ports:
    - "2205:22"
  # ------------------------------------------------
  node-6:
    <<: *node
    hostname: node-6
    ports:
    - "2206:22"

#####################

# networks:
#   rancher:

# volumes:
#   rancher:
